# Generated by Django 5.1.3 on 2025-01-08 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_customuser_is_admin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="gender",
            field=models.CharField(
                blank=True, choices=[("male", "Male"), ("female", "Female")], null=True
            ),
        ),
    ]
