# Generated by Django 5.1.3 on 2025-01-05 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files_store", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="filestore",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="filestore",
            name="file_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="filestore",
            name="unique_code",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
