# Generated by Django 5.1.3 on 2025-01-06 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files_store", "0002_filestore_comment_alter_filestore_file_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="filestore",
            name="file_size",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="filestore",
            name="last_downloaded",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
